batch_size: 64
epochs: 500

optimizer: { initial_lr: 0.005, epsilon: 0.00000001 }
reduce_lr: { factor: 0.1, patience: 5, min_lr: 0.00005, monitor: val_loss }

early_stopping: { monitor: val_loss, patience: 15, verbose: 1 }
